

from __future__ import annotations

import os
import json
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
import textwrap

import streamlit as st
from dotenv import load_dotenv

import pdfminer.high_level
import chromadb
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

import openai

from pydantic import BaseModel, ValidationError
import re

# For PDF generation
from io import BytesIO
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.pdfgen import canvas
    REPORTLAB_AVAILABLE = True
except Exception:
    REPORTLAB_AVAILABLE = False



load_dotenv()



OPENAI_MODEL = os.getenv("EXAM_GEN_MODEL", "gpt-4o-mini")
EMBED_MODEL_NAME = os.getenv("EMBED_MODEL_NAME", "text-embedding-3-small")
DEFAULT_TEMPERATURE = 0.3


# ---------------------------------------------------------------------------
# Data structures

@dataclass
class UnitSpec:
    """A course unit with a name and relative weight/credit hours."""

    name: str
    weight: float


@dataclass
class TypeSpec:
    """Specification for a particular question type in the exam blueprint."""

    qtype: str
    count: int
    difficulty: str
    marks: int


class Question(BaseModel):
    """A single question generated by the LLM."""

    id: str
    unit: str
    type: str
    difficulty: str
    prompt: str
    choices: Optional[List[Dict[str, str]]] = None
    answer: str
    explanation: Optional[str] = None
    marks: Optional[int] = None
    source_ids: List[str]


class ExamPaper(BaseModel):
    """The full exam paper with sections and answer key."""

    title: str
    instructions: str
    sections: Dict[str, List[Question]]
    answer_key: Dict[str, Tuple[str, List[str]]]


# ---------------------------------------------------------------------------
# Document store for RAG

class DocumentStore:


    def __init__(self, persist_dir: str = ".chromadb"):
        self.client = chromadb.PersistentClient(path=persist_dir)
        api_key = os.getenv("OPENAI_API_KEY")
        self.embedding_fn = OpenAIEmbeddingFunction(api_key=api_key, model_name=EMBED_MODEL_NAME)
        self.collection = self.client.get_or_create_collection(
            name="documents", embedding_function=self.embedding_fn
        )
        base_path = os.path.join(os.path.dirname(__file__), "knowledge_base")
        try:
            self._load_initial_documents(base_path)
        except Exception:
            pass

    def _split_text(self, text: str, chunk_size: int = 1000, overlap: int = 200) -> List[str]:
        paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
        chunks: List[str] = []
        current = ""
        for para in paragraphs:
            if len(current) + len(para) <= chunk_size:
                current += para + " "
            else:
                chunks.append(current.strip())
                current = para + " "
        if current.strip():
            chunks.append(current.strip())
        return chunks

    def add_document(self, name: str, text: str, source_type: str = "user") -> int:
        chunks = self._split_text(text)
        ids = [f"{name}_chunk_{i}" for i in range(len(chunks))]
        metadatas = [
            {"source": name, "chunk_index": i, "source_type": source_type}
            for i in range(len(chunks))
        ]
        try:
            existing_ids = [doc_id for doc_id in ids if doc_id in self.collection.get()["ids"]]
            if existing_ids:
                self.collection.delete(ids=existing_ids)
        except Exception:
            pass
        self.collection.add(documents=chunks, ids=ids, metadatas=metadatas)
        return len(chunks)

    def _document_present(self, name: str) -> bool:
        try:
            ids = self.collection.get()["ids"]
        except Exception:
            ids = []
        prefix = f"{name}_chunk_"
        return any(doc_id.startswith(prefix) for doc_id in ids)

    def _load_initial_documents(self, base_path: str) -> None:
        if not os.path.isdir(base_path):
            return
        for file_name in os.listdir(base_path):
            if not file_name.lower().endswith(".pdf"):
                continue
            name = file_name
            if self._document_present(name):
                continue
            file_path = os.path.join(base_path, file_name)
            try:
                with open(file_path, "rb") as f:
                    pdf_bytes = f.read()
                from io import BytesIO
                text = pdfminer.high_level.extract_text(BytesIO(pdf_bytes)) or ""
                if text.strip():
                    self.add_document(name, text, source_type="knowledge_base")
            except Exception:
                continue

    def query(
        self,
        query: str,
        top_k: int = 3,
        source_types: Optional[List[str]] = None,
    ) -> List[Tuple[str, str]]:
        
        result = self.collection.query(
            query_texts=[query],
            n_results=top_k * 5,
            include=["documents", "metadatas", "distances"],
        )
        documents = result.get("documents", [[]])[0]
        ids = result.get("ids", [[]])[0]
        metadatas = result.get("metadatas", [[]])[0]
        matches: List[Tuple[str, str]] = []
        for doc_text, doc_id, meta in zip(documents, ids, metadatas):
            if source_types is None or meta.get("source_type") in source_types:
                matches.append((doc_text, doc_id))
                if len(matches) >= top_k:
                    break
        return matches

    def get_texts_by_ids(self, ids: List[str]) -> List[str]:
        if not ids:
            return []
        try:
            result = self.collection.get(ids=ids, include=["documents"])
            texts = []
            for doc_list in result.get("documents", []):
                if doc_list:
                    texts.append(doc_list[0])
            return texts
        except Exception:
            return ["<unavailable>"] * len(ids)


# ---------------------------------------------------------------------------
# LLM interface

def build_prompt(context: str, type_spec: TypeSpec, unit_name: str) -> List[Dict[str, str]]:
    system_msg = {
        "role": "system",
        "content": (
            "You are an expert assessment designer. You generate exam questions in strict JSON format. You generate question based on context retrieved from knowledge base"
            "Return only JSON with a single top‑level key 'questions'."
        ),
    }
    user_content = (
        f"Context:\n{context}\n\n"
        f"You are creating exam questions for the unit '{unit_name}'.\n"
        f"Question type: {type_spec.qtype}\n"
        f"Difficulty level: {type_spec.difficulty}\n"
        f"Number of questions: {type_spec.count}\n"
        f"Marks per question: {type_spec.marks}\n"
        "Return a JSON object with key 'questions'. Each question must include: "
        "'type', 'difficulty', 'prompt', 'choices' (for MCQ only with labels A–D), "
        "'answer', 'explanation' (optional), and 'marks'. Do not include commentary or additional keys."
    )
    user_msg = {"role": "user", "content": user_content}
    return [system_msg, user_msg]


def ask_openai(messages: List[Dict[str, str]]) -> Dict[str, any]:
    client = openai.OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    response = client.chat.completions.create(
        model=OPENAI_MODEL,
        messages=messages,
        temperature=DEFAULT_TEMPERATURE,
        response_format={"type": "json_object"},
    )
    content = response.choices[0].message.content
    return json.loads(content)


def generate_questions_for_unit(
    unit: UnitSpec,
    type_spec: TypeSpec,
    doc_store: DocumentStore,
    syllabus_snippet: str = "",
) -> List[Question]:
    retrieval_query = f"{unit.name} {type_spec.qtype} {type_spec.difficulty}".strip()
    if syllabus_snippet:
        retrieval_query = f"{retrieval_query} {syllabus_snippet.strip()}"
    top_k = max(3, type_spec.count)
    retrieved = doc_store.query(
        retrieval_query,
        top_k=top_k,
        source_types=["knowledge_base"],
    )
    context_text = "\n\n".join([doc for doc, _ in retrieved])
    source_ids = [chunk_id for _, chunk_id in retrieved]
    messages = build_prompt(context_text, type_spec, unit.name)
    raw_json = ask_openai(messages)
    qlist = raw_json.get("questions", [])
    questions: List[Question] = []
    for idx, qdict in enumerate(qlist):
        q_id = f"{unit.name.replace(' ', '_')}_{type_spec.qtype}_{idx+1}"
        choices = qdict.get("choices")
        if choices and isinstance(choices, dict):
            normalized = []
            for label, text in choices.items():
                normalized.append({"label": label, "text": text})
            choices = normalized
        try:
            question = Question(
                id=q_id,
                unit=unit.name,
                type=qdict.get("type", type_spec.qtype),
                difficulty=qdict.get("difficulty", type_spec.difficulty),
                prompt=qdict["prompt"],
                choices=choices,
                answer=qdict["answer"],
                explanation=qdict.get("explanation"),
                marks=qdict.get("marks", type_spec.marks),
                source_ids=source_ids,
            )
        except ValidationError as ve:
            raise ValueError(f"Invalid question structure: {ve}")
        questions.append(question)
    return questions


def allocate_counts(total: int, weights: List[float]) -> List[int]:
    if total <= 0 or not weights:
        return [0] * len(weights)
    weight_sum = sum(weights)
    if weight_sum <= 0:
        base = total // len(weights)
        alloc = [base] * len(weights)
        for i in range(total % len(weights)):
            alloc[i] += 1
        return alloc
    quotas = [(w / weight_sum) * total for w in weights]
    allocations = [int(q) for q in quotas]
    remainder = [q - a for q, a in zip(quotas, allocations)]
    remaining = total - sum(allocations)
    for _ in range(remaining):
        idx = remainder.index(max(remainder))
        allocations[idx] += 1
        remainder[idx] = 0
    return allocations


def create_pdf_from_markdown(md_text: str) -> bytes:
    if not REPORTLAB_AVAILABLE:
        return b""
    buffer = BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    y = height - 72
    line_height = 14
    for line in md_text.split("\n"):
        if y < 72:
            c.showPage()
            y = height - 72
        c.drawString(72, y, line)
        y -= line_height
    c.save()
    buffer.seek(0)
    return buffer.getvalue()


def extract_units_from_documents(doc_store: DocumentStore) -> List[UnitSpec]:
    units: List[UnitSpec] = []
    seen: set[str] = set()
    try:
        result = doc_store.collection.get(include=["documents", "metadatas"])
        all_docs = result.get("documents", [])
    except Exception:
        return [UnitSpec(name="Unit1", weight=1.0)]
    for doc_chunks in all_docs:
        for text in doc_chunks:
            for line in text.split("\n"):
                m = re.match(r"\s*(?:Unit|UNIT)\s*(\d+)\s*[:\-–.]?\s*(.*)", line)
                if not m:
                    continue
                number = m.group(1)
                title = m.group(2).strip()
                if title:
                    unit_name = f"Unit {number}: {title}"
                else:
                    unit_name = f"Unit {number}"
                weight = 1.0
                weight_match = re.search(r"(\d+(?:\.\d+)?)\s*(credit|credits|hours|hrs)", line, re.IGNORECASE)
                if weight_match:
                    try:
                        weight = float(weight_match.group(1))
                    except Exception:
                        weight = 1.0
                if unit_name not in seen:
                    units.append(UnitSpec(name=unit_name, weight=weight))
                    seen.add(unit_name)
    if not units:
        units.append(UnitSpec(name="Unit1", weight=1.0))
    return units


def generate_exam(
    units: List[UnitSpec],
    type_specs: List[TypeSpec],
    doc_store: DocumentStore,
    exam_title: str = "Summative Assessment",
    instructions: str = "Answer all questions. Read each section carefully.",
    syllabus_snippet: str = "",
) -> ExamPaper:
    sections: Dict[str, List[Question]] = {}
    answer_key: Dict[str, Tuple[str, List[str]]] = {}
    for type_spec in type_specs:
        if type_spec.count <= 0:
            continue
        weights = [u.weight for u in units]
        per_unit_counts = allocate_counts(type_spec.count, weights)
        type_questions: List[Question] = []
        for unit_spec, unit_count in zip(units, per_unit_counts):
            if unit_count <= 0:
                continue
            unit_type_spec = TypeSpec(
                qtype=type_spec.qtype,
                count=unit_count,
                difficulty=type_spec.difficulty,
                marks=type_spec.marks,
            )
            qs = generate_questions_for_unit(unit_spec, unit_type_spec, doc_store, syllabus_snippet)
            type_questions.extend(qs)
        if type_questions:
            sections[type_spec.qtype] = type_questions
            for q in type_questions:
                answer_key[q.id] = (q.answer, q.source_ids)
    return ExamPaper(
        title=exam_title,
        instructions=instructions,
        sections=sections,
        answer_key=answer_key,
    )


def extract_text_from_pdf(file_bytes: bytes) -> str:
    from io import BytesIO
    with BytesIO(file_bytes) as buffer:
        return pdfminer.high_level.extract_text(buffer) or ""


def main() -> None:
    st.set_page_config(page_title="AI Exam Creator – Real World", layout="wide")
    st.title("AI Exam Creator – Real World Edition")
    st.markdown(
        """
        Upload your reference documents in the sidebar, define your exam blueprint
        (units, weights and question types) and generate a complete exam.

        **Note:** AI‑generated questions are a starting point.  Experts must
        validate the content before use【692816959653244†L82-L93】.
        """
    )

    if "doc_store" not in st.session_state:
        st.session_state["doc_store"] = DocumentStore(persist_dir=".exam_documents")
        st.session_state["documents"] = []

    doc_store: DocumentStore = st.session_state["doc_store"]

    with st.sidebar:
        st.header("Reference Library")
        add_mode = st.radio(
            "Add reference content by:",
            options=["Upload File", "Paste Text"],
            index=0,
            help="Select whether you want to upload a PDF/text file or paste text directly."
        )
        if add_mode == "Upload File":
            uploaded_docs = st.file_uploader(
                "Upload PDF or text files", type=["pdf", "txt"], accept_multiple_files=True
            )
            if uploaded_docs:
                for doc in uploaded_docs:
                    name = doc.name
                    file_bytes = doc.read()
                    try:
                        if name.lower().endswith(".pdf"):
                            text = extract_text_from_pdf(file_bytes)
                        else:
                            text = file_bytes.decode("utf-8", errors="ignore")
                        num_chunks = doc_store.add_document(name, text, source_type="user")
                        st.session_state["documents"].append((name, num_chunks))
                        st.success(f"Added {name} with {num_chunks} chunks to library.")
                    except Exception as exc:
                        st.error(f"Failed to ingest {name}: {exc}")
        else:
            doc_title = st.text_input(
                "Document Title", value="", placeholder="Enter a name for this text document"
            )
            doc_text = st.text_area(
                "Document Text", value="", height=150, placeholder="Paste your syllabus or reference text here"
            )
            if st.button("Add Text to Library"):
                if doc_text.strip():
                    name = doc_title.strip() or f"Text_{len(st.session_state['documents']) + 1}"
                    try:
                        num_chunks = doc_store.add_document(name, doc_text, source_type="user")
                        st.session_state["documents"].append((name, num_chunks))
                        st.success(f"Added {name} with {num_chunks} chunks to library.")
                    except Exception as exc:
                        st.error(f"Failed to ingest text: {exc}")
                else:
                    st.error("Please provide some text before adding to the library.")
        if st.button("Clear Library"):
            try:
                all_ids = doc_store.collection.get()["ids"]
                doc_store.collection.delete(ids=all_ids)
                st.session_state["documents"] = []
                st.success("Cleared the document library.")
            except Exception as exc:
                st.error(f"Failed to clear library: {exc}")
        if st.session_state["documents"]:
            st.subheader("Loaded Documents")
            for name, num in st.session_state["documents"]:
                st.caption(f"{name} – {num} chunks")

    st.header("Exam Configuration")
    exam_title = st.text_input("Exam Title", value="Summative Assessment")
    instructions = st.text_area(
        "Instructions", value="Answer all questions. Read each section carefully.", height=3
    )
    st.subheader("Syllabus Content (Optional)")
    syllabus_snippet = st.text_area(
        "Paste relevant syllabus or outline text",
        value="",
        height=4,
        placeholder="Paste key topics or paragraphs from your syllabus here. The system will use this text to retrieve matching content from your knowledge base.",
        help="Providing syllabus text helps the AI find related passages in your reference documents. Leave blank to rely only on unit names."
    )
    st.subheader("Units and Weights")
    manual_units = st.checkbox(
        "Specify units and weights manually", value=False,
        help="Check this if units and credit hours are not clearly defined in the uploaded documents or if you wish to override them."
    )
    units: List[UnitSpec] = []
    if manual_units:
        unit_count = st.number_input(
            "Number of units/topics", min_value=1, max_value=10, value=1, step=1
        )
        for i in range(int(unit_count)):
            cols = st.columns(2)
            unit_name = cols[0].text_input(f"Unit {i+1} Name", key=f"unit_name_{i}")
            unit_weight = cols[1].number_input(
                f"Unit {i+1} Weight (credit hours)", min_value=0.0, step=0.5, value=1.0, key=f"unit_weight_{i}"
            )
            units.append(UnitSpec(name=unit_name or f"Unit{i+1}", weight=unit_weight))
    else:
        units = extract_units_from_documents(doc_store)
    st.subheader("Question Blueprint")
    type_specs: List[TypeSpec] = []
    def add_type_row(label: str, default_count: int, key_prefix: str) -> Optional[TypeSpec]:
        with st.expander(label):
            count = st.number_input(
                f"Number of {label} questions", min_value=0, max_value=50, value=default_count, step=1,
                key=f"count_{key_prefix}"
            )
            difficulty = st.selectbox(
                f"Difficulty for {label}", options=["Easy", "Moderate", "Hard"],
                index=0 if label == "MCQs" else 1, key=f"difficulty_{key_prefix}"
            )
            marks = st.number_input(
                f"Marks per {label} question", min_value=1, max_value=50, value=1, step=1,
                key=f"marks_{key_prefix}"
            )
            if count > 0:
                return TypeSpec(qtype=label.rstrip("s"), count=int(count), difficulty=difficulty, marks=int(marks))
        return None
    maybe_mcq = add_type_row("MCQs", default_count=5, key_prefix="mcq")
    maybe_tf = add_type_row("True/False", default_count=3, key_prefix="tf")
    maybe_sa = add_type_row("Short Answer", default_count=2, key_prefix="sa")
    maybe_la = add_type_row("Long Answer", default_count=1, key_prefix="la")
    maybe_case = add_type_row("Case Study", default_count=0, key_prefix="case")
    for spec in [maybe_mcq, maybe_tf, maybe_sa, maybe_la, maybe_case]:
        if spec is not None:
            type_specs.append(spec)
    if st.button("Generate Exam"):
        has_docs = bool(doc_store.collection.get()["ids"])
        if not has_docs:
            st.error("Please add at least one reference document or paste text into the library before generating.")
        elif not units or all(u.weight == 0 for u in units):
            st.error("Please define at least one unit with a positive weight.")
        elif not type_specs:
            st.error("Please configure at least one question type with count > 0.")
        else:
            with st.spinner("Generating exam… this may take a moment"):
                try:
                    paper = generate_exam(
                        units=units,
                        type_specs=type_specs,
                        doc_store=doc_store,
                        exam_title=exam_title,
                        instructions=instructions,
                        syllabus_snippet=syllabus_snippet,
                    )
                except Exception as exc:
                    st.error(f"Error generating exam: {exc}")
                    return
            st.subheader(paper.title)
            st.markdown(paper.instructions)
            for qtype, qs in paper.sections.items():
                st.markdown(f"### {qtype}")
                for i, q in enumerate(qs, start=1):
                    st.markdown(f"#### Q{i} ({q.difficulty})")
                    new_prompt = st.text_area(
                        label=f"Edit prompt for {q.id}", value=q.prompt, key=f"prompt_{q.id}", height=80
                    )
                    if new_prompt != q.prompt:
                        q.prompt = new_prompt
                    if q.choices:
                        updated_choices = []
                        for choice in q.choices:
                            label = choice["label"]
                            text_val = st.text_input(
                                label=f"{label}.",
                                value=choice["text"],
                                key=f"choice_{q.id}_{label}",
                            )
                            updated_choices.append({"label": label, "text": text_val})
                        q.choices = updated_choices
                    q.explanation = None
                    paper.answer_key[q.id] = (q.answer, q.source_ids)
            st.markdown("---")
            st.markdown("## Answer Key")
            for qid, (ans, sources) in paper.answer_key.items():
                st.markdown(f"- **{qid}**: {ans}")
                top_sources = sources[:3]
                source_texts = doc_store.get_texts_by_ids(top_sources)
                for idx, sid in enumerate(top_sources):
                    doc_name = sid.split("_chunk_")[0] if "_chunk_" in sid else sid
                    text = source_texts[idx] if idx < len(source_texts) else ""
                    clean = text.strip().replace("\n", " ")
                    snippet = clean[:500]
                    wrapped = textwrap.fill(snippet, width=80)
                    st.markdown(f"  - Source {idx+1} ({doc_name}):")
                    st.markdown(wrapped)
            try:
                exam_json = paper.model_dump_json(indent=2)
            except Exception:
                exam_json = json.dumps(paper.model_dump(), indent=2)
            st.download_button(
                label="Download Exam JSON",
                data=exam_json,
                file_name="exam_paper.json",
                mime="application/json",
            )
            md_parts = []
            md_parts.append(f"# {paper.title}\n")
            md_parts.append(paper.instructions + "\n")
            for qtype, qs in paper.sections.items():
                md_parts.append(f"\n## {qtype}\n")
                for i, q in enumerate(qs, start=1):
                    md_parts.append(f"**Q{i} ({q.difficulty})** {q.prompt}\n")
                    if q.choices:
                        for choice in q.choices:
                            md_parts.append(f"- {choice['label']}. {choice['text']}\n")
                    md_parts.append("\n")
            md_parts.append("\n---\n# Answer Key\n")
            for qid, (ans, sources) in paper.answer_key.items():
                md_parts.append(f"- **{qid}**: {ans}\n")
                top_sources = sources[:3]
                source_texts = doc_store.get_texts_by_ids(top_sources)
                for idx, sid in enumerate(top_sources):
                    doc_name = sid.split("_chunk_")[0] if "_chunk_" in sid else sid
                    text = source_texts[idx] if idx < len(source_texts) else ""
                    clean = text.strip().replace("\n", " ")
                    snippet = clean[:500]
                    wrapped = textwrap.fill(snippet, width=80)
                    md_parts.append(f"  - Source {idx+1} ({doc_name}):\n")
                    for line in wrapped.split("\n"):
                        md_parts.append(f"    {line}\n")
            md_text = "".join(md_parts)
            st.download_button(
                label="Download Exam Markdown",
                data=md_text,
                file_name="exam_paper.md",
                mime="text/markdown",
            )
            if REPORTLAB_AVAILABLE:
                pdf_data = create_pdf_from_markdown(md_text)
                st.download_button(
                    label="Download Exam PDF",
                    data=pdf_data,
                    file_name="exam_paper.pdf",
                    mime="application/pdf",
                )


if __name__ == "__main__":
    main()